name: Update Checker

env:
  REPO_URL: https://github.com/graysky2/openwrt
  REPO_BRANCH: master
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
  schedule:
    - cron: 30 18 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get Commit Hash
        id: getHash
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
          echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v5
        with:
          path: .commitHash
          key: commitHash_${{ steps.getHash.outputs.commitHash }}

      - name: Save New Commit Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo "${{ steps.getHash.outputs.commitHash }}" | tee .commitHash

      - name: Trigger build
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ github.token }}
          event-type: Source Code Update
